### ISSUE TITLE
Packager fails to deliver files

### ISSUE THREAD

**Issue by ahanriat** [mrpatiwi/ReactNativeTS#12]
Hi guys! I wanted to enjoy the SourceMap, but I've ran into some issues :/

When debugging with chrome it tries to open files, but the packager logs a 404 error (see screenshot) . The result is a blank file in the chrome debugger.
I've tried to open **.ts|.js|.tsx|node_modules files** without success

![screen_shot_2017-02-20_at_14_09_34](https://cloud.githubusercontent.com/assets/1374161/23126346/86438ba4-f776-11e6-97d8-c9716cb1b0cc.png)

Thanks for your help

**Comment by llaine** [comment]
Any updates on this ? @mrpatiwi

**Comment by lopezjurip** [comment]
There was #5, but is not working anymore because of: https://github.com/mhzed/react-native-sm-transformer/issues/2
