### ISSUE TITLE
Cherry pick enhancements from derived demo?

### ISSUE THREAD

**Issue by inakianduaga** [mrpatiwi/ReactNativeTS#17]
Hi,

Thanks for the project! I took it as the starting point of a demo I'm working on, I did some upgrades and fixes (latest typescript versions, updated TS config, HMR working w/ redux, immutableJS integration). It's a bit more opinionated than a bare boilerplate:

https://github.com/inakianduaga/react-native-demo

Maybe you can merge some changes back? I would love to do a PR back to this project but I'm afraid I don't have much time for that at the moment.

**Comment by lopezjurip** [comment]
Thanks! I will check it out and see what can I take

**Comment by lopezjurip** [comment]
Done! #18
