### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by ghost** [mrpatiwi/ReactNativeTS#2]
Hi, I am new to react-native and never heard of Typescript before I saw your project on an awsome-list.
I want to user flyx, alt and Typescript, but unable to start the 'alt' branch.

The result is:
<img width="374" alt="screenshot 2015-12-13 13 14 28" src="https://cloud.githubusercontent.com/assets/61650/11766928/c05181e8-a19b-11e5-8a4c-044c47a94a29.png">

I did as follow:
[Terminal Saved Output.txt](https://github.com/mrpatiwi/ReactNativeTS/files/60448/Terminal.Saved.Output.txt)

When gulp watch, I opened XCode, opened the IOS project, let the indexing finish and the run it.

Do you know what is wrong?

**Comment by lopezjurip** [comment]
Make sure you have installed `react-native-cli`:

``` sh
npm install -g react-native-cli
```

Then start the server using:

``` sh
npm start
```

`gulp watch` must work together with this.

>  You should run this two commands on different terminal sessions.

**Comment by ghost** [comment]
Ok, I installed react-native-cli. `npm start` don't work.

[Terminal Saved Output.txt](https://github.com/mrpatiwi/ReactNativeTS/files/60451/Terminal.Saved.Output.txt)

**Comment by ghost** [comment]
I managed to get it running by installing react-native-cli as dev depency: `npm install --save-dev react-native-cli`. I then started XCode to get iPhone 6s simulation, got the same error.

**Comment by lopezjurip** [comment]
I'm having the same error.
See `built/index.ios.js`, it should not do this:

``` ts
var react_native_1 = require("react-native");
const { StyleSheet, Text, View } = react_native_1.default;
```

It should:

``` ts
var react_native_1 = require("react-native");
const { StyleSheet, Text, View } = react_native_1;
```

I'm looking how to fix it

**Comment by lopezjurip** [comment]
Ok, first let's update our typings:

``` sh
tsd install react-native --save
```

Then remove `"module": "commonjs"` from `tsconfig.json`.
And make sure that `gulp` is compiling the files, **not your IDE** (I use Atom + Atom-Typescript).

**Comment by ghost** [comment]
Ok, thank fixed it.

Could you please be so kind what `"module": "commonjs"` was meant to be doing?

**Comment by lopezjurip** [comment]
I wish I knew
