### ISSUE TITLE
Issue react_1["default"]

### ISSUE THREAD

**Issue by FeFB** [mrpatiwi/ReactNativeTS#4]
Hi, 

I tried to use this new project. First following the stpes: npm install =>"npm start", in a new console I executed "npm run android" (with the emulator already opened), and it is working. 
However, when I change something in src/index.android.tsx and save it, the emulator is showing a error. 
I already saw the error in the old version in a closed issue #2 , I tried update my tsd, but it is not working.
I am using Atom with Atom-typescript. 
npm --version  3.10.6
react-native-cli: 1.0.0
react-native: 0.31.0

When I executed npm install, a npm  warn showed me "react-native@0.31.0 requires a peer of react@~15.2.1 but none was installed", so I changed the react version to 15.2.1 in package.json  and executed npm install again, but the error keep coming up.
![screenshot_20160826-124721](https://cloud.githubusercontent.com/assets/10860505/18012222/000600d0-6b8f-11e6-834f-1dff232740d1.png)

What am I missing?
Thanks by the way.

**Comment by lopezjurip** [comment]
Sometimes Atom-Typescript "transpiles" the Typescript skipping the information from `tsconfig.json`. I recommend disabled the `compileOnSave` option.

**Comment by FeFB** [comment]
@mrpatiwi Yes, it fixed the issue. 
Do you have some tip to compile the files when I save it on Atom? I tried to use on sublime 3, with compileOnSave: true, but it is not working. I need to build all the project to see the changes on the emulator.

Thanks for the help, I am new with Typescript and reacts packages.

**Comment by lopezjurip** [comment]
Try:

``` sh
npm run build -- --watch
```

**Comment by FeFB** [comment]
@mrpatiwi  
Yes, It is working great with Hot Reloading Enable. :)  Thanks for the changes and the attention.
